### ISSUE TITLE
Add support for html colors

### ISSUE THREAD

**Issue by Gunni** [soxofaan/duviz#11]
Depends on #9 ofcourse

Basically i'd like to pipe the output of this script to something called xymon.

It could be neat!

**Comment by soxofaan** [comment]
You mean rendering to HTML markup and colors? or just HTML colors (not sure what that would mean though)?

**Comment by Gunni** [comment]
Here is an example from a script I made:

![Screenshot from 2019-11-01 16-56-10](https://user-images.githubusercontent.com/358099/68041584-c88f3d00-fcc8-11e9-96fe-5a0d086ac55a.png)

**Comment by zivanfi** [comment]
This may be accomplised by piping the output into `aha` from https://github.com/theZiz/aha (also available in several linux distributions).
