### ISSUE TITLE
Package duviz and publish to pypi

### ISSUE THREAD

**Issue by soxofaan** [soxofaan/duviz#2]
as noted in jlevy/the-art-of-command-line#108:

> Have you considered publishing your package to pypi? It's not hard.
> Once you do that, I'd suggest PRing it to https://github.com/alebcay/awesome-shell

**Comment by sudomilk** [comment]
If there is anything I can do to assist, let me know. This is an awesome tool.

**Comment by soxofaan** [comment]
duviz is on pypi now: https://pypi.org/project/duviz/

Also tried to get it in homebrew: https://github.com/Homebrew/homebrew-core/pull/22472 but github page of duviz is not popular enough apperently. Made a workaround for it though: 60cc29e1eeac3fb5d5ab18c508737efb1122a310  60e0d437653ac3aaad9a67ecc784a0bd3085ed0e
