### ISSUE TITLE
brew Error

### ISSUE THREAD

**Issue by berot3** [soxofaan/duviz#28]
I just tried `brew install https://raw.github.com/soxofaan/duviz/master/extra/homebrew/duviz.rb`
and got this

```
Error: Non-checksummed download of duviz formula file from an arbitrary URL is unsupported! `brew extract` or `brew create` and `brew tap-new` to create a formula file in a tap on GitHub instead.
```

**Comment by soxofaan** [comment]
hmm, I guess homebrew tightened up security around `brew install`ing from an URL

did you get around that with one of the suggestions in the error message?

**Comment by soxofaan** [comment]
homebrew installation should now work with:

    brew install soxofaan/duviz/duviz
